package com.compliancehub.utils;

import lombok.Data;

import java.util.*;


@Data
public class Locations {
    public static Set<String> locations = new HashSet<>(); // Hashset is FAST as F

    // define da groups here
    public final static Set<String> EU = new HashSet<>(Arrays.asList("AUSTRIA", "BELGIUM", "BULGARIA", "CROATIA", "CYPRUS", "CZECHIA", "DENMARK", "ESTONIA", "FINLAND", "FRANCE", "GERMANY", "GREECE", "HUNGARY", "IRELAND", "ITALY", "LATVIA", "LITHUANIA", "LUXEMBOURG", "MALTA", "NETHERLANDS", "POLAND", "PORTUGAL", "ROMANIA", "SLOVAKIA", "SLOVENIA", "SPAIN", "SWEDEN"));
    public final static Set<String> EEA = new HashSet<>(Arrays.asList("AUSTRIA", "BELGIUM", "BULGARIA", "CROATIA", "CYPRUS", "CZECHIA", "DENMARK", "ESTONIA", "FINLAND", "FRANCE", "GERMANY", "GREECE", "HUNGARY", "IRELAND", "ITALY", "LATVIA", "LITHUANIA", "LUXEMBOURG", "MALTA", "NETHERLANDS", "POLAND", "PORTUGAL", "ROMANIA", "SLOVAKIA", "SLOVENIA", "SPAIN", "SWEDEN", "NORWAY", "LICHTENSTEIN", "ICELAND"));
    public final static Set<String> NORTH_AMERICA = new HashSet<>(Arrays.asList("ANTIGUA AND BARBUDA", "BAHAMAS", "BARBADOS", "BELIZE", "CANADA", "COSTA RICA", "CUBA", "DOMINICA", "DOMINIAN REPUBLiC", "EL SALVADOR", "GRENADA", "GUATEMALA", "HAITI", "HONDURAS", "JAMAICE", "MEXICO", "NICARAGUA", "PANAMA", "SAINT KITTS AND NEVIS", "SAINT LUCIA", "SAINT VINCENT AND THE GRENADINES", "TRINIDAD AND TOBAGO", "UNITED STATES"));

    public final static Map<String, Set<String>> groups = new HashMap<>();
    // create groups here
    static {
        groups.put("EEA", EEA);
        groups.put("EU", EU);
        groups.put("NORTH AMERICA", NORTH_AMERICA);
        // ... More groups here, if ya know any!  ! !
    }

    static { // All the countriez/locations here
        locations.add("UNDEFINED");
        locations.add("AFGHANISTAN");
        locations.add("ÅLAND ISLANDS");
        locations.add("ALBANIA");
        locations.add("ALGERIA");
        locations.add("AMERICAN SAMOA");
        locations.add("ANDORRA");
        locations.add("ANGOLA");
        locations.add("ANGUILLA");
        locations.add("ANTARCTICA");
        locations.add("ANTIGUA AND BARBUDA");
        locations.add("ARGENTINA");
        locations.add("ARMENIA");
        locations.add("ARUBA");
        locations.add("AUSTRALIA");
        locations.add("AUSTRIA");
        locations.add("AZERBAIJAN");
        locations.add("BAHAMAS");
        locations.add("BAHRAIN");
        locations.add("BANGLADESH");
        locations.add("BARBADOS");
        locations.add("BELARUS");
        locations.add("BELGIUM");
        locations.add("BELIZE");
        locations.add("BENIN");
        locations.add("BERMUDA");
        locations.add("BHUTAN");
        locations.add("BOLIVIA, PLURINATIONAL STATE OF");
        locations.add("BONAIRE, SINT EUSTATIUS AND SABA");
        locations.add("BOSNIA AND HERZEGOVINA");
        locations.add("BOTSWANA");
        locations.add("BOUVET ISLAND");
        locations.add("BRAZIL");
        locations.add("BRITISH INDIAN OCEAN TERRITORY");
        locations.add("BRUNEI DARUSSALAM");
        locations.add("BULGARIA");
        locations.add("BURKINA FASO");
        locations.add("BURUNDI");
        locations.add("CAMBODIA");
        locations.add("CAMEROON");
        locations.add("CANADA");
        locations.add("CAPE VERDE");
        locations.add("CAYMAN ISLANDS");
        locations.add("CENTRAL AFRICAN REPUBLIC");
        locations.add("CHAD");
        locations.add("CHILE");
        locations.add("CHINA");
        locations.add("CHRISTMAS ISLAND");
        locations.add("COCOS (KEELING) ISLANDS");
        locations.add("COLOMBIA");
        locations.add("COMOROS");
        locations.add("CONGO");
        locations.add("CONGO, THE DEMOCRATIC REPUBLIC OF THE");
        locations.add("COOK ISLANDS");
        locations.add("COSTA RICA");
        locations.add("CÔTE D'IVOIRE");
        locations.add("CROATIA");
        locations.add("CUBA");
        locations.add("CURAÇAO");
        locations.add("CYPRUS");
        locations.add("CZECH REPUBLIC");
        locations.add("DENMARK");
        locations.add("DJIBOUTI");
        locations.add("DOMINICA");
        locations.add("DOMINICAN REPUBLIC");
        locations.add("ECUADOR");
        locations.add("EGYPT");
        locations.add("EL SALVADOR");
        locations.add("EQUATORIAL GUINEA");
        locations.add("ERITREA");
        locations.add("ESTONIA");
        locations.add("ETHIOPIA");
        locations.add("FALKLAND ISLANDS (MALVINAS)");
        locations.add("FAROE ISLANDS");
        locations.add("FIJI");
        locations.add("FINLAND");
        locations.add("FRANCE");
        locations.add("FRENCH GUIANA");
        locations.add("FRENCH POLYNESIA");
        locations.add("FRENCH SOUTHERN TERRITORIES");
        locations.add("GABON");
        locations.add("GAMBIA");
        locations.add("GEORGIA");
        locations.add("GERMANY");
        locations.add("GHANA");
        locations.add("GIBRALTAR");
        locations.add("GREECE");
        locations.add("GREENLAND");
        locations.add("GRENADA");
        locations.add("GUADELOUPE");
        locations.add("GUAM");
        locations.add("GUATEMALA");
        locations.add("GUERNSEY");
        locations.add("GUINEA");
        locations.add("GUINEA-BISSAU");
        locations.add("GUYANA");
        locations.add("HAITI");
        locations.add("HEARD ISLAND AND MCDONALD ISLANDS");
        locations.add("HOLY SEE (VATICAN CITY STATE)");
        locations.add("HONDURAS");
        locations.add("HONG KONG");
        locations.add("HUNGARY");
        locations.add("ICELAND");
        locations.add("INDIA");
        locations.add("INDONESIA");
        locations.add("IRAN, ISLAMIC REPUBLIC OF");
        locations.add("IRAQ");
        locations.add("IRELAND");
        locations.add("ISLE OF MAN");
        locations.add("ISRAEL");
        locations.add("ITALY");
        locations.add("JAMAICA");
        locations.add("JAPAN");
        locations.add("JERSEY");
        locations.add("JORDAN");
        locations.add("KAZAKHSTAN");
        locations.add("KENYA");
        locations.add("KIRIBATI");
        locations.add("KOREA, DEMOCRATIC PEOPLE'S REPUBLIC OF");
        locations.add("KOREA, REPUBLIC OF");
        locations.add("KUWAIT");
        locations.add("KYRGYZSTAN");
        locations.add("LAO PEOPLE'S DEMOCRATIC REPUBLIC");
        locations.add("LATVIA");
        locations.add("LEBANON");
        locations.add("LESOTHO");
        locations.add("LIBERIA");
        locations.add("LIBYA");
        locations.add("LIECHTENSTEIN");
        locations.add("LITHUANIA");
        locations.add("LUXEMBOURG");
        locations.add("MACAO");
        locations.add("MACEDONIA, THE FORMER YUGOSLAV REPUBLIC OF");
        locations.add("MADAGASCAR");
        locations.add("MALAWI");
        locations.add("MALAYSIA");
        locations.add("MALDIVES");
        locations.add("MALI");
        locations.add("MALTA");
        locations.add("MARSHALL ISLANDS");
        locations.add("MARTINIQUE");
        locations.add("MAURITANIA");
        locations.add("MAURITIUS");
        locations.add("MAYOTTE");
        locations.add("MEXICO");
        locations.add("MICRONESIA, FEDERATED STATES OF");
        locations.add("MOLDOVA, REPUBLIC OF");
        locations.add("MONACO");
        locations.add("MONGOLIA");
        locations.add("MONTENEGRO");
        locations.add("MONTSERRAT");
        locations.add("MOROCCO");
        locations.add("MOZAMBIQUE");
        locations.add("MYANMAR");
        locations.add("NAMIBIA");
        locations.add("NAURU");
        locations.add("NEPAL");
        locations.add("NETHERLANDS");
        locations.add("NEW CALEDONIA");
        locations.add("NEW ZEALAND");
        locations.add("NICARAGUA");
        locations.add("NIGER");
        locations.add("NIGERIA");
        locations.add("NIUE");
        locations.add("NORFOLK ISLAND");
        locations.add("NORTHERN MARIANA ISLANDS");
        locations.add("NORWAY");
        locations.add("OMAN");
        locations.add("PAKISTAN");
        locations.add("PALAU");
        locations.add("PALESTINE, STATE OF");
        locations.add("PANAMA");
        locations.add("PAPUA NEW GUINEA");
        locations.add("PARAGUAY");
        locations.add("PERU");
        locations.add("PHILIPPINES");
        locations.add("PITCAIRN");
        locations.add("POLAND");
        locations.add("PORTUGAL");
        locations.add("PUERTO RICO");
        locations.add("QATAR");
        locations.add("RÉUNION");
        locations.add("ROMANIA");
        locations.add("RUSSIAN FEDERATION");
        locations.add("RWANDA");
        locations.add("SAINT BARTHÉLEMY");
        locations.add("SAINT HELENA, ASCENSION AND TRISTAN DA CUNHA");
        locations.add("SAINT KITTS AND NEVIS");
        locations.add("SAINT LUCIA");
        locations.add("SAINT MARTIN (FRENCH PART)");
        locations.add("SAINT PIERRE AND MIQUELON");
        locations.add("SAINT VINCENT AND THE GRENADINES");
        locations.add("SAMOA");
        locations.add("SAN MARINO");
        locations.add("SAO TOME AND PRINCIPE");
        locations.add("SAUDI ARABIA");
        locations.add("SENEGAL");
        locations.add("SERBIA");
        locations.add("SEYCHELLES");
        locations.add("SIERRA LEONE");
        locations.add("SINGAPORE");
        locations.add("SINT MAARTEN (DUTCH PART)");
        locations.add("SLOVAKIA");
        locations.add("SLOVENIA");
        locations.add("SOLOMON ISLANDS");
        locations.add("SOMALIA");
        locations.add("SOUTH AFRICA");
        locations.add("SOUTH GEORGIA AND THE SOUTH SANDWICH ISLANDS");
        locations.add("SOUTH SUDAN");
        locations.add("SPAIN");
        locations.add("SRI LANKA");
        locations.add("SUDAN");
        locations.add("SURINAME");
        locations.add("SVALBARD AND JAN MAYEN");
        locations.add("SWAZILAND");
        locations.add("SWEDEN");
        locations.add("SWITZERLAND");
        locations.add("SYRIAN ARAB REPUBLIC");
        locations.add("TAIWAN, PROVINCE OF CHINA");
        locations.add("TAJIKISTAN");
        locations.add("TANZANIA, UNITED REPUBLIC OF");
        locations.add("THAILAND");
        locations.add("TIMOR-LESTE");
        locations.add("TOGO");
        locations.add("TOKELAU");
        locations.add("TONGA");
        locations.add("TRINIDAD AND TOBAGO");
        locations.add("TUNISIA");
        locations.add("TURKEY");
        locations.add("TURKMENISTAN");
        locations.add("TURKS AND CAICOS ISLANDS");
        locations.add("TUVALU");
        locations.add("UGANDA");
        locations.add("UKRAINE");
        locations.add("UNITED ARAB EMIRATES");
        locations.add("UNITED KINGDOM");
        locations.add("UNITED STATES");
        locations.add("UNITED STATES MINOR OUTLYING ISLANDS");
        locations.add("URUGUAY");
        locations.add("UZBEKISTAN");
        locations.add("VANUATU");
        locations.add("VENEZUELA, BOLIVARIAN REPUBLIC OF");
        locations.add("VIET NAM");
        locations.add("VIRGIN ISLANDS, BRITISH");
        locations.add("VIRGIN ISLANDS, U.S.");
        locations.add("WALLIS AND FUTUNA");
        locations.add("WESTERN SAHARA");
        locations.add("YEMEN");
        locations.add("ZAMBIA");
        locations.add("ZIMBABWE");

    }

}




