name: backend tests

on:
  push:
    paths:
      - backend/**

jobs:
  build_test:
    runs-on: ubuntu-latest
    steps:
      # Tjekkede kildekoden ud
      - uses: actions/checkout@v3

      # Installer JDK 21
      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven

      # Byg og test backend
      - name: Build backend
        run: |
          cd backend 
          mvn clean package -DskipTests